server:
  socket:
    port: ${SOCKET_PORT}

spring:
  jpa:
    database: mysql
  datasource:
    url: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
 
auth:
  jwt:
    secret: ${JWT_SECRET}
